apiVersion: 1
datasources:
  - access: proxy
    uid: PBFA97CFB590B2093
    editable: true
    name: prometheus
    type: prometheus
    url: https://openformat-graph-node-prometheus.fly.dev
    basicAuth: true
    basicAuthUser: ${PROMETHEUS_USER}
    secureJsonData:
      basicAuthPassword: ${PROMETHEUS_PASS}
    version: 1
