# fly.toml app configuration file generated for openformat-graph-node-prometheus on 2025-04-15T02:08:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openformat-graph-node-prometheus'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
source = "prometheus_data"
destination = "/prometheus"