global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "graph-node"
    static_configs:
      - targets: ["openformat-graph-node-staging.internal:8040"]
    metrics_path: "/metrics"
    scheme: http
