# fly.toml app configuration file generated for openformat-grafana on 2024-03-25T12:33:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openformat-graph-node-grafana'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
